Proprietary content. ©Great Learning. All Rights Reserved. Unauthorized use or distribution prohibited

In [1]:
pip install sklearn

  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1321 sha256=a4936b9613bb66b914ead8488274ec64b038b3b952f757cc15e3be86ccb95a9a
  Stored in directory: c:\users\ranjan mitra\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


In [4]:

import re, string, unicodedata                          # Import Regex, string and unicodedata.
import contractions                                     # Import contractions library.
from bs4 import BeautifulSoup                           # Import BeautifulSoup.

import numpy as np                                      # Import numpy.
import pandas as pd                                     # Import pandas.
import nltk                                             # Import Natural Language Tool-Kit.

nltk.download('stopwords')                              # Download Stopwords.
nltk.download('punkt')
nltk.download('wordnet')


[nltk_data] Downloading package stopwords to C:\Users\Ranjan
[nltk_data]     Mitra\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\Ranjan
[nltk_data]     Mitra\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Ranjan
[nltk_data]     Mitra\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
# list of text documents
text = ['This is the first stage of qualification'
, 'This is the second stage of qualification '
, 'And the third one'
, 'Is it the first stage again']
# create the transform
myvocab={'again': 0, 'and': 1, 'first': 2, 'is': 3, 'it': 4, 'of': 5, 'one': 6, 'qualification': 7, 'second': 8, 'stage': 9, 'the': 10, 'this': 11}
vectorizer = CountVectorizer(analyzer='word', binary=False, decode_error='strict',
dtype=np.int64, encoding='utf-8', input='content',
lowercase=True, max_df=1.0, max_features=5, min_df=1,
ngram_range=(1, 1), preprocessor=None, stop_words=None,
strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
tokenizer=None, vocabulary=myvocab)
## all_features = vectorizer.get_feature_names() 
# tokenize and build vocab
vectorizer.fit(text)
# summarize
print(vectorizer.vocabulary_)
# encode document
vector = vectorizer.transform(text)
# summarize encoded vector
print(vector.shape)
print(type(vector))
print(vector.toarray())
print('vectorizer.get_feature_names(): {0}'.format(vectorizer.get_feature_names()))


{'again': 0, 'and': 1, 'first': 2, 'is': 3, 'it': 4, 'of': 5, 'one': 6, 'qualification': 7, 'second': 8, 'stage': 9, 'the': 10, 'this': 11}
(4, 12)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 1 1 0 1 0 1 0 1 1 1]
 [0 0 0 1 0 1 0 1 1 1 1 1]
 [0 1 0 0 0 0 1 0 0 0 1 0]
 [1 0 1 1 1 0 0 0 0 1 1 0]]
vectorizer.get_feature_names(): ['again', 'and', 'first', 'is', 'it', 'of', 'one', 'qualification', 'second', 'stage', 'the', 'this']


# encode another document
text2 = ["passion fruit is a vine species of passion flower"]
vector = vectorizer.transform(text2)
print(vector.toarray())
print(vector.shape)

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
# list of text documents
text = ['This is the first stage of qualification'
, 'This is the second stage of qualification '
, 'And the third one'
, 'Is it the first stage again']
# create the transform
vectorizer = TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
dtype=np.float64, encoding='utf-8',
input='content', lowercase=True, max_df=1.0, max_features=None,
min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
smooth_idf=True, stop_words=None, strip_accents=None,
sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
tokenizer=None, use_idf=True, vocabulary=None)
# tokenize and build vocab
vectorizer.fit(text)
idf = vectorizer.idf_
# summarize
print(vectorizer.vocabulary_)
print(vectorizer.idf_)
#get  Feature name 
print(dict(zip(vectorizer.get_feature_names(), idf)))
# encode document
vector = vectorizer.transform([text[0]])
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

{'this': 12, 'is': 3, 'the': 10, 'first': 2, 'stage': 9, 'of': 5, 'qualification': 7, 'second': 8, 'and': 1, 'third': 11, 'one': 6, 'it': 4, 'again': 0}
[1.91629073 1.91629073 1.51082562 1.22314355 1.91629073 1.51082562
 1.91629073 1.51082562 1.91629073 1.22314355 1.         1.91629073
 1.51082562]
{'again': 1.916290731874155, 'and': 1.916290731874155, 'first': 1.5108256237659907, 'is': 1.2231435513142097, 'it': 1.916290731874155, 'of': 1.5108256237659907, 'one': 1.916290731874155, 'qualification': 1.5108256237659907, 'second': 1.916290731874155, 'stage': 1.2231435513142097, 'the': 1.0, 'third': 1.916290731874155, 'this': 1.5108256237659907}
(1, 13)
[[0.         0.         0.41706663 0.33765138 0.         0.41706663
  0.         0.41706663 0.         0.33765138 0.27605213 0.
  0.41706663]]


In [11]:
!pip install TextBlob
from textblob import TextBlob
text=TextBlob('This is the first stage of qualification'
, 'This is the second stage of qualification '
, 'And the third one'
, 'Is it the first stage again')
print(text.sentiment)

ValueError: tokenizer must be an instance of BaseTokenizer

In [ ]:
!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
text=SentimentIntensityAnalyzer()
score=text.polarity_scores('This is the first stage of qualification'
, 'This is the second stage of qualification '
, 'And the third one'
, 'Is it the first stage again')
print(score)
